apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: demo-app
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          annotations:
            autoscaling.knative.dev/minScale: "0"
        spec:
          container:
            image: gcr.io/knative-demo-1/demo-app:latest