apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: demo-app
spec:
  source:
    git:
      url: "https://github.com/mycegcpdemo/demo-knative.git"
      revision: "master"
    subPath: "flask-example/"
  steps:
  - name: build-and-push
    image: "gcr.io/kaniko-project/executor:v0.6.0"
    args:
    - "--dockerfile=/workspace/Dockerfile"
    - "--destination=gcr.io/knative-demo-1/demo-app:latest"